language: node_js
node_js:
  - 'node'
  - 'lts/*'
  - '10'
env:
  - MOCHA_VERSION=8
  - MOCHA_VERSION=7
  - MOCHA_VERSION=6
cache: npm
install:
  - npm install mocha@$MOCHA_VERSION
  - npm install
after_success:
  - npm run report-coverage
